# Эта конфигурация запускает кластер Kafka в KRaft режиме (без Zookeeper) с разделением ролей:
# 3 контроллера (Controller Nodes): controller-1, controller-2, controller-3. Их роль строго ограничена управлением метаданными кластера.
# 3 брокера (Broker Nodes): broker-1, broker-2, broker-3. Они отвечают за хранение и обработку данных (топиков и партиций).
# Фактор репликации по умолчанию не задан явно в этой конфигурации на уровне брокеров. Он обычно указывается при создании топика.
# + Регистр схем. (Без интерфейса. Проверить: curl http://localhost:8081/config -> "{"compatibilityLevel":"BACKWARD"}% ")
# kafka-ui (вместо Kafdrop) по адресу http://localhost:8088/ (в нем можно смотреть регистр схем!)
# Запускается (!)

version: "3"
services:

  # https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html

  controller-1:
    image: confluentinc/cp-kafka:7.6.1
    hostname: controller-1
    container_name: controller-1
    environment:
      KAFKA_PROCESS_ROLES: "controller"
      KAFKA_NODE_ID: 1
      # На каком сокете слушает:
      KAFKA_LISTENERS: "CONTROLLER://controller-1:29092"
      # Участники кворума при определении лидера:
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092,2@controller-2:29092,3@controller-3:29092"
      # По какому префиксу искать первого слушателя при KRaft:
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  controller-2:
    image: confluentinc/cp-kafka:7.6.1
    hostname: controller-2
    container_name: controller-2
    depends_on:
      - controller-1
    # Убраны порты 9093:9092 и 9102:9101, так как контроллеры обычно не требуют внешних портов для клиентов
    environment:
      KAFKA_PROCESS_ROLES: "controller"
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: "CONTROLLER://controller-2:29092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092,2@controller-2:29092,3@controller-3:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  controller-3:
    image: confluentinc/cp-kafka:7.6.1
    hostname: controller-3
    container_name: controller-3
    depends_on:
      - controller-1
      - controller-2
    # Убраны порты 9094:9092 и 9103:9101, см. комментарий выше
    environment:
      KAFKA_PROCESS_ROLES: "controller"
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: "CONTROLLER://controller-3:29092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092,2@controller-2:29092,3@controller-3:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  broker-1:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker-1
    container_name: broker-1
    ports:
      - "9095:9092"       # Внутренний порт 9092 для общения внутри Docker
      - "9091:29092"      # Изменено: Внешний порт 9091 хоста -> 29092 контейнера
      - "9104:9101"       # JMX
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: "broker"
      # Префикс слушателя у контроллера:
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # Префикс слушателя для внутреннего общения брокеров:
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      # Изменено: broker-1 слушает на 29092 для внешнего соединения
      KAFKA_LISTENERS: "PLAINTEXT://broker-1:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      # Пары префикс слушателя - протокол безопасности:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      # Изменено: Адрес, по которому внешние клиенты будут подключаться с хоста
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-1:9092,PLAINTEXT_HOST://host.docker.internal:9091"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092,2@controller-2:29092,3@controller-3:29092"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  broker-2:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker-2
    depends_on:
      - broker-1
    container_name: broker-2
    ports:
      - "9096:9092"       # Внутренний порт 9092 для общения внутри Docker
      - "9092:29092"      # Изменено: Внешний порт 9092 хоста -> 29092 контейнера
      - "9105:9101"       # JMX
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      # Изменено: Адрес, по которому внешние клиенты будут подключаться с хоста
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-2:9092,PLAINTEXT_HOST://host.docker.internal:9092"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092,2@controller-2:29092,3@controller-3:29092"
      # Изменено: broker-2 слушает на 29092 для внешнего соединения
      KAFKA_LISTENERS: "PLAINTEXT://broker-2:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  broker-3:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker-3
    depends_on:
      - broker-2
    container_name: broker-3
    ports:
      - "9097:9092"       # Внутренний порт 9092 для общения внутри Docker
      - "9093:29092"      # Изменено: Внешний порт 9093 хоста -> 29092 контейнера
      - "9106:9101"       # JMX
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      # Изменено: Адрес, по которому внешние клиенты будут подключаться с хоста
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-3:9092,PLAINTEXT_HOST://host.docker.internal:9093"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092,2@controller-2:29092,3@controller-3:29092"
      # Изменено: broker-3 слушает на 29092 для внешнего соединения
      KAFKA_LISTENERS: "PLAINTEXT://broker-3:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  # https://docs.confluent.io/platform/current/schema-registry/installation/config.html

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - broker-1 # Зависимость оставлена, но Schema Registry подключается по внутреннему адресу
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      # Подключение к брокеру по внутреннему адресу в Docker сети
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker-1:9092
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      # Фактор репликации для служебного топика Schema Registry
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1

  # https://docs.kafka-ui.provectus.io/configuration/configuration-file

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:master
    ports:
      - 8088:8080
    depends_on:
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      # Подключение к брокерам по внутренним адресам в Docker сети (остаётся без изменений)
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://broker-1:9092,broker-2:9092,broker-3:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'